[build-system]
build-backend = 'py_build_cmake.build'
requires = ['py-build-cmake~=0.4.3']

[project]
name = 'cminpack_numba'
version= '0.1.4'
description = 'A numba compatible wrapper of cminpack.'
readme = 'README.md'
license = {file = 'LICENSE'}
authors = [{name = 'Chris Ninham', email = 'christopher.ninham@creatis.insa-lyon.fr'},]
dependencies = [
    "numba",
    "numpy",
] # TODO(nin17): Add version of numba & numpy required
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "scipy>=1.15.3",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ['ALL']
ignore = ['TD003']

[tool.ruff.extend-per-file-ignores]
'chkder.py' = ['ANN001', 'ANN201', 'ANN202', 'ARG001', 'D103', 'PLR0913']
'dpmpar.py' = ['ANN001', 'ANN202', 'ARG001']
'enorm.py' = ['ANN001', 'ANN202', 'ARG001']
'hybrd.py' = ['ANN001', 'ANN202', 'ARG001', 'ARG005', 'PLR0913']
'hybrj.py' = ['ANN001', 'ANN202', 'ARG001', 'ARG005', 'PLR0913']
'lmder.py' = ['ANN001', 'ANN202', 'ARG001', 'ARG005', 'PLR0913']
'lmdif.py' = ['ANN001', 'ANN202', 'ARG001', 'ARG005', 'PLR0913']
'lmstr.py' = ['ANN001', 'ANN202', 'ARG001', 'ARG005', 'PLR0913']
'utils.py' = ['ANN001', 'ANN202', 'ARG001', 'D103']
'tests/*' = ['ANN001', 'ARG001', 'ANN201', 'D103']
'tests/test_hybrj.py' = ['PLR0913',]
'tests/test_lmder.py' = ['ANN202', 'PLR0913', 'PLR2004']
'tests/test_lmdif.py' = ['ANN202', 'PLR0913', 'PLR2004']
'tests/test_lmstr.py' = ['ANN202', 'PLR0913', 'PLR2004']

[tool.pyright]
reportInvalidTypeForm = false

[tool.py-build-cmake.module]
directory = '.'

[tool.py-build-cmake.sdist]
include = ['subprojects/cminpack/CMakeLists.txt', 'subprojects/cminpack/*']

[tool.py-build-cmake.cmake]
minimum_version = '3.17'
build_type = 'RelWithDebInfo'
source_path = 'subprojects/cminpack'
build_args = ['-j']
[tool.py-build-cmake.cmake.options]
BUILD_SHARED_LIBS = 'ON'
USE_BLAS = 'OFF' # TODO(nin17): Add blas support
CMINPACK_LIB_INSTALL_DIR='cminpack_numba'


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]